### ISSUE TITLE
Compatibility with Rails 4.1.x

### ISSUE THREAD

**Issue by lluchez** [blocknotes/activeadmin_quill_editor#10]
Hi,

The gemspec file has the following dependency:
```
spec.add_runtime_dependency 'activeadmin', '>= 1.0'
```
It prevents the gem to work on Rails `4.1.x` as the compatible version of activeadmin is `1.0.0.pre`.

As i'm currently in the process of upgrading an old app I wanted replace our current WYSIWYG editor by `activeadmin_quill_editor` first before bumping the Rails version to `4.2.0` but it's not allowed with the current restriction.

I forked the repo and I was able to relax the version dependency and it worked on Rails `4.1.16`: https://github.com/lluchez/activeadmin_quill_editor/commit/dd9637c1dcfc1082c18b886761291a1e9a9d9821

Please let me know if this repo is still maintained and this is something that can be changed (or I can submit a PR if easier). Otherwise I'll just use my own fork.

Thank you.
Lio

**Comment by blocknotes** [comment]
Sorry for replying so late.
To keep compatibility with older Rails versions seems a special case which could be handled in a user fork, IMO.
Closing this one.
