### ISSUE TITLE
Add more options to image_uploader

### ISSUE THREAD

**Issue by kwent** [blocknotes/activeadmin_quill_editor#16]
Hi

First, thanks for this amazing library. Life saver !!

I had like to use https://lokeshdhakar.com/projects/lightbox2/#examples

Somehow i need to get this library to return 

```html
<a href="images/image-1.jpg" data-lightbox="image-1" data-title="My caption">Image #1</a>
```

My proposal would be to make `image_uploader` a bit more flexible like:

```ruby
plugin_opts = { 
  image_uploader: {
    server_url: upload_admin_post_path(object.id),
    field_name: 'file_upload',
    html_element: 'a',
    html_options: { data: { lightbox: 'image-1', title: 'My caption' }, class: 'myclass' }
   }
}
```

Thoughts ?

Regards

**Comment by blocknotes** [comment]
Hey @kwent, you mean the element inserted in the editor?
I think this is handled by the image plugin, I would take a look there to see if it is possible to do it:
https://github.com/NoelOConnell/quill-image-uploader

**Comment by kwent** [comment]
Found a way without hacking this with https://kingdido999.github.io/zooming/
