### ISSUE TITLE
Is it possible to fix a max length for the quill editor input ?

### ISSUE THREAD

**Issue by Emilie-thp** [blocknotes/activeadmin_quill_editor#27]
I cannot find an easy way to limit **max length** of my quill editor input ? 
Does anyone know how to do it ? 

I tried to add a `maxlength: 50` in the { input_html } but it is not working....

My quill editor input looks like this for now : 
```
      f.input :description,
                  as: :quill_editor,
                  input_html: {
                    data: {
                      options: {
                        modules: {
                          toolbar: [
                            ['bold', 'underline'],
                            [{ 'list': 'bullet' }]
                          ]
                        }
                      }
                    }
                  }
```

thanks a lot

**Comment by blocknotes** [comment]
Hey @Emilie-thp,
it's tricky to limit the length of HTML content because it also includes tags.
If you limit the length in some way the string could break the HTML structure.
With a fixed length string I would avoid an HTML editor.

**Comment by Emilie-thp** [comment]
Hello @blocknotes, 
I see, thanks for your reply !
