### ISSUE TITLE
Inputs not shown on first page load

### ISSUE THREAD

**Issue by vccoffey** [blocknotes/activeadmin_quill_editor#32]
We are running a Rails 6.1.6 app with shakapacker 6.3.0.

On the first time loading a particular page, the quill text inputs do not render, there is just an empty `<li>` element where the input should be.

On a refresh, or any subsequent visit to that page (the edit page of a particular resource), the quill editor inputs will be displayed correctly.

Seems to be some kind of browser cacheing issue, but I can't track it down. No console errors are thrown.

**Comment by vccoffey** [comment]
Tracked down the issue, the bug was not in [activeadmin_quill_editor](https://github.com/blocknotes/activeadmin_quill_editor)

**Comment by blocknotes** [comment]
Hey @vccoffey.
Thanks for reporting, I have no experience with `shakapacker` but I heard of it.
If it's not something strictly related to your app and if you want to share the solution, perhaps it could help someone else.
