### ISSUE TITLE
(Action Text) Does't display content in the editor

### ISSUE THREAD

**Issue by Civil21** [blocknotes/activeadmin_quill_editor#33]
**Dependencies:** 
```
- Rails (7.0.3)
- Ruby (3.1)
- activeadmin_quill_editor (1.0.0)
```
**Situation:**
If used with Action Text there is a problem. When editing, the editor is empty because it is not possible to read the input content due to `<div class="trix-content">some html content</div>`

Of course, this is not a problem of the gem, but since it is recommended to use it when you need to work with Action Text in the active admin, it is worth offering a solution.

**My solution** (hardcode):
```
project/app/models/some_model.rb

has_rich_text :text

def some_text=(body)
 text.body = body
end

def some_text
   text.to_s.gsub(/\A<div class="trix-content">(.*)<\/div>\z/m, '\1').strip.html_safe
end
```

**Comment by EricRoos** [comment]
Thank you for this!

**Comment by acollazomayer** [comment]
@Civil21 can you please explain the solution a little bit better. I am not being able to make it work. Thanks!

**Comment by CamilaUlmetePais** [comment]
> @Civil21 can you please explain the solution a little bit better. I am not being able to make it work. Thanks!

I second this! Please @Civil21 , if at all possible, could you explain how this works?

**Comment by BBVishalkumar** [comment]
> text.to_s.gsub(/\A<div class="trix-content">(.*)<\/div>\z/m, '\1').strip.html_safe

Hello Can you explain how this worked

**Comment by BBVishalkumar** [comment]
> Thank you for this!

Can you explain how this worked @EricRoos

**Comment by blocknotes** [comment]
Hey @Civil21 and the other users: I'm sorry to comment so late on this issue 😓 

> **Situation:** If used with Action Text there is a problem. When editing, the editor is empty because it is not possible to read the input content due to `<div class="trix-content">some html content</div>`
> Of course, this is not a problem of the gem, but since it is recommended to use it when you need to work with Action Text in the active admin, it is worth offering a solution.

_activeadmin_quill_editor_ supports only plain text or string fields.
ActionText (or any other field wrapper) could interfere with the editor functions, as in this case.
So I would suggest to avoid mixing components in this way.

That said, I provide a different solution - because from my standpoint - overriding the model's methods is not the best, you could break ActionText functions then.

I would use a decorator instead: https://activeadmin.info/11-decorators.html

My example:

```
# app/models/book.rb
class Book < ApplicationRecord
  has_rich_text :content
end

# app/admin/books.rb
class BookDecorator < Draper::Decorator
  delegate_all

  def content
    super.to_s
  end
end

ActiveAdmin.register Book do
  decorate_with BookDecorator

  permit_params :content

  form decorate: true do |f|
    f.input :content, as: :quill_editor
  end

  show do
    attributes_table do
      row :content do |book|
        book.content.to_s
      end
    end
  end
end
```

I'm closing the issue.

**Comment by blocknotes** [comment]
Here it is another alternative version using getter/setter methods (in case you prefer to avoid having a decorator object).

A sample model:

```rb
# app/models/author.rb
class Author < ApplicationRecord
  has_rich_text :description

  def quill_description
    self.description.to_s
  end

  def quill_description=(value)
    self.description = value
  end
end
```

The admin model configuration:

```rb
# app/admin/authors.rb
ActiveAdmin.register Author do
  permit_params :name, :email, :age, :quill_description

  show do
    attributes_table do
      row :name
      row :email
      row :age
      row :quill_description
    end
    active_admin_comments
  end

  form do |f|
    f.inputs 'Author' do
      f.input :name
      f.input :email
      f.input :age
      f.input :quill_description, as: :quill_editor
    end

    f.actions
  end
end
```

**Comment by BBVishalkumar** [comment]
Hi @blocknotes 
This is able to show the text but not able to show  the color 
suppose i have made my text  in red color  now when i update it and again edit it it not showing the red color why?

**Comment by BBVishalkumar** [comment]
Hi @blocknotes 
For showing the color and background color and other text coloring stuff 
we need to update  the method 
 def quill_description
    self.description&.body&.html_safe
 end

**Comment by BBVishalkumar** [comment]
` def quill_description
    self.description&.body&.html_safe
  end`

**Comment by blocknotes** [comment]
> Hi @blocknotes For showing the color and background color and other text coloring stuff we need to update the method `def quill_description self.description&.body&.html_safe end`

Thank you @BBVishalkumar - I update my last answer 👍
