### ISSUE TITLE
Unable to Add New Fonts in Quill Editor

### ISSUE THREAD

**Issue by dilip49** [blocknotes/activeadmin_quill_editor#39]
**Description**:
I've been attempting to add new fonts to the Quill editor, but I'm facing a persistent issue where only the "sans-serif" font is displayed by default. Even when I try to add other fonts, it merely duplicates "sans-serif" in the dropdown menu. I've explored various solutions, including re-configuring the gem, but I haven't been able to resolve the problem.

**Code snippet:**

```
f.input :description, as: :quill_editor, input_html: {
        value: strip_tags(f.object.description),
        class: 'quill_text',
        data: {
          options: {
            modules: {
              toolbar: [
                ['bold', 'italic', 'underline'],
                ['link'],
                [{ 'font': ['Source Sans Pro', 'sans-serif'] }]
              }
            },
            formats: ['bold', 'italic', 'underline', 'link', 'font']
          }
        }
      }

```
**Screenshot:**
<img width="681" alt="Screenshot 2023-09-07 at 12 13 36 AM" src="https://github.com/blocknotes/activeadmin_quill_editor/assets/49529495/0d88a2cd-dd05-4ec3-9e87-37ea3c807a7c">

**Additional Information:**
Gem Version: activeadmin_quill_editor (1.0.0)

This appears to be a potential issue, and I'd greatly appreciate any assistance in resolving it. Thank you in advance for your help.

**Comment by blocknotes** [comment]
Hi @dilip49,
thank you for your issue.

After some checks, it doesn't look like an issue related to _activeadmin_quill_editor_ gem.

If you try with: `[{ 'font': [] }]` - you should get:

<img width="653" alt="image" src="https://github.com/blocknotes/activeadmin_quill_editor/assets/6893256/2fc55838-307d-42f6-b2b5-b2a92c42da44">

If you try with: `[{ 'font': %w[sans-serif arial serif] }]` - you should get:

<img width="642" alt="image" src="https://github.com/blocknotes/activeadmin_quill_editor/assets/6893256/7a305e5d-d3f7-4a77-a7be-42b651244179">

I think that you need to register the custom fonts as proposed in the Quill docs (they aren't very clear perhaps, but there are some examples in Stackoverflow):
https://quilljs.com/guides/how-to-customize-quill/#customizing-attributors

**Comment by blocknotes** [comment]
I'm closing the issue
