### ISSUE TITLE
Content Not shown in Edit Form

### ISSUE THREAD

**Issue by pavan-kumarv** [blocknotes/activeadmin_quill_editor#40]
Content is not show in edit form

```ruby
activeadmin version - 2.13.0
```

active admin non webpack version

This is the show page
![Screenshot 2024-01-09 at 6 42 12 PM](https://github.com/blocknotes/activeadmin_quill_editor/assets/120575892/eb8429c4-72e9-4145-882f-8891fb5fb655)

This is the edit page
![Screenshot 2024-01-09 at 6 41 56 PM](https://github.com/blocknotes/activeadmin_quill_editor/assets/120575892/41348f34-4ee1-4f1c-b88d-fd1cb07f5340)

**Comment by BBVishalkumar** [comment]
Hi @pavan-kumarv  i am also getting same issues of not showing content of the descrition because when we write
  f.input :description, as: :quill_editor
  then its will show the value which is presnet in description fields not what is store in .rich_text_description&.body&.html_safe

**Comment by BBVishalkumar** [comment]
@pavan-kumarv 
check this close pr
https://github.com/blocknotes/activeadmin_quill_editor/issues/33

**Comment by blocknotes** [comment]
Hey @pavan-kumarv
As pointed out also by @BBVishalkumar, the rich text feature is not compatible with _activeadmin_quill_editor_
If you are using it, please try to comment the `has_rich_text` line to check if the issue is related.

**Comment by pavan-kumarv** [comment]
Thanks for responding @blocknotes and @BBVishalkumar 

Sad to know it does not work with `ActionText`, if I comment out `has_rich_text` how will I be able to use the rich text, because `has_rich_text` helper will take care of storing these html content with images and stuff. I tried commenting the `has_rich_text` but obviously was throwing error.

Is there way to add support to this, because it works while creating, but does not work while updating, I suspect there should be a way.

I am all relied on this package, other packages are not working as expected specially for image upload.

let me know if I can help in any ways.

**Comment by blocknotes** [comment]
@pavan-kumarv: can you try using a decorator as I proposed [here](https://github.com/blocknotes/activeadmin_quill_editor/issues/33#issuecomment-1748383784)?

**Comment by pavan-kumarv** [comment]
> @pavan-kumarv: I proposed another solution here: [#33 (comment)](https://github.com/blocknotes/activeadmin_quill_editor/issues/33#issuecomment-1965996947)
> 
> It should address the issue.

Thank You @blocknotes This worked for me 🎉
