### ISSUE TITLE
File to import not found or unreadable: activeadmin/quill_editor/quill.snow.

### ISSUE THREAD

**Issue by lironbeni** [blocknotes/activeadmin_quill_editor#5]
I did all you instructed in the guide but yet I keep getting the same error:
**File to import not found or unreadable: activeadmin/quill_editor/quill.snow.**

* I added to my Gemfile:
gem 'activeadmin_quill_editor', git: 'https://github.com/blocknotes/activeadmin_quill_editor', branch: 'aa2'
* run Bundle install
* added this to active_admin.scss:
@import 'activeadmin/quill_editor_input';
* added this to active_admin.js:
//= require activeadmin/quill_editor/quill
//= require activeadmin/quill_editor_input

And no luck....
Help please :)

**Comment by lironbeni** [comment]
Bundle install worked and added this:

> +GIT
+  remote: https://github.com/blocknotes/activeadmin_quill_editor
+  revision: 21806ca9b46a68ed2023344c7979b834ba94f5b9
+  branch: aa2
+  specs:
+    activeadmin_quill_editor (0.1.4)
+      activeadmin (= 2.0.0.alpha)
+
 GEM
   remote: https://rubygems.org/
   specs:
@@ -337,6 +345,7 @@ DEPENDENCIES
   active_admin_paranoia
   active_model_serializers
   activeadmin!
+  activeadmin_quill_editor!
   awesome_print
   bootsnap (>= 1.1.0)
   byebug

**Comment by blocknotes** [comment]
Hi @lironbeni 
I have just pushed a small change on that branch (aa2)
Could you please try a:
`bundle update activeadmin_quill_editor`
?

**Comment by kwent** [comment]
@blocknotes `AA 2.0.0` is now released. Time to update the master branch of this awesome library ?  Regards

**Comment by blocknotes** [comment]
AA support added
